[ Create ] 상세페이지 ProductView 구현
wecode-bootcamp-korea/27-2nd-SUULGO-backend pull request #4
Opened 2021-12-15 16:25 UTC by Daco2020

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 유저 리스트 중 하나를 클릭하면 나타나는 상대 유저의 상세페이지 뷰를 제작하였습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상세페이지에 필요한 데이터들을 반환합니다.
2. 디비에 숫자로 저장된 stack, alcohol_limit의 값들은 함수를 통해 프론트에게 필요한 문자로 변환되어 반환됩니다.(enum을 사용하지 못했습니다..)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 스스로 함수를 만들어 데이터를 수정 후 반환 할 수 있음을 알게 되었습니다.
- enum을 사용하려고 했지만 키가 프론트로부터 받는 값들과 달라서 이를 어떻게 연결해야할지 고민하였습니다. 어떻게든 연결해서 이용할 수는 있겠지만 그것이 일반적인 함수를 만드는 것보다 더 효율적인지는 모르겠습니다.. 

<br />

## :: 기타 질문 및 특이 사항
- enum을 적어두긴 했지만 사용하지는 않았습니다. enum을 이용해서 디비에 저장된 숫자값을 반환해줄 수 있을지, 또는 들어온 값을 숫자로 바꿔 저장해줄 수 있을지, 그리고 그것이 효율적인지는 아직 잘 모르겠습니다..

2021-12-16 02:02 UTC, bigfanoftim commented
Postman 결과값은 텍스트가 아닌 indent가 보기 좋게 잘 맞춰진 스크린샷으로 반영해주시면 더 좋을 것 같아요~

2021-12-16 02:53 UTC, lordmyshepherd requested changes
유닛테스트 추가해서 오려주세요~

2021-12-16 02:53 UTC, lordmyshepherd commented on core/utils.py
> +        return ""
if문을 사용하지 않고 dictionary로 만들어주세요.
```suggestion
     t = { }
     ..
```
로직은 선형성을 갖도록 만들어주시는 것이 좋습니다. if문을 많이 사용하는 경우에는 그만큼 로직이 갈라지기 때문에 많은 if은 dictionary로 변경하므로써 로직을 선형적으로 만들어줄 수 있습니다.

2021-12-16 02:53 UTC, lordmyshepherd commented on core/utils.py
> +        return ""
아래와 마찬가지로 수정해보세요~

2021-12-16 11:28 UTC, Daco2020 commented on core/utils.py
> +        return ""
수정하였습니다!

2021-12-16 11:28 UTC, Daco2020 commented on core/utils.py
> +        return ""
딕셔너리로 바꾸어 수정하였습니다.

2021-12-16 11:32 UTC, Daco2020 commented
리뷰내용 반영하였으며, 추가로 이넘 관련하여 디비에 테이블 추가하였습니다. 모델에 오타가 있어 일부 수정하였고, 로그인 사용자 정보를 얻기 위해 데코레이터를 추가하였습니다. 마지막으로 테스트 진행까지 모두 완료하였습니다.

2021-12-17 06:13 UTC, Daco2020 commented
회원가입시 반드시 서베이를 작성해야하기 때문에 로그인 유저의 서베이 존재여부를 체크하는 함수를 추가하였습니다.

2021-12-17 09:43 UTC, jamessoun93 requested changes

2021-12-17 09:43 UTC, jamessoun93 commented on core/utils.py
> +    return alcohol_limit_dict.get(i)
dictionary 만 가지고도 해당 기능을 구현할 수 있는데 이 부분이 굳이 함수까지 필요한 부분은 아닌 것 같네요.
사용할 클래스에서 직접 구현해주셔도 무방합니다.

2021-12-17 09:43 UTC, jamessoun93 commented on users/tests.py
> +    #     self.assertEqual(response.status_code, 401)
이 부분은 사용하지 않는 코드이니 없애고 올려주세요.

2021-12-17 09:43 UTC, jamessoun93 commented on users/views.py
> +from users.models           import Survey, Mbti, Gender, Meeting, SurveyDrinkingMethod, DrinkingMethod, SurveyFlavor, Flavor, SurveyAlcoholCategory, AlcoholCategory, User
이 정도로 많으면 그냥 와일드카드(*) 로 import 해주시는게 더 가독성이 좋을 수 있겠네요!

2021-12-17 09:43 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({ "message" : "DoesNotExist" }, status=401)
DoesNotExist 와 어울리지 않는 http status code 입니다. `401` 은 어떤 의미를 갖는 http status code 일까요?

2021-12-17 12:24 UTC, Daco2020 commented on core/utils.py
> +    return alcohol_limit_dict.get(i)
네! 수정하였습니다!

2021-12-17 12:24 UTC, Daco2020 commented on users/tests.py
> +    #     self.assertEqual(response.status_code, 401)
네 삭제하였습니다~!

2021-12-17 12:24 UTC, Daco2020 commented on users/views.py
> +from users.models           import Survey, Mbti, Gender, Meeting, SurveyDrinkingMethod, DrinkingMethod, SurveyFlavor, Flavor, SurveyAlcoholCategory, AlcoholCategory, User
넵 수정하였습니다~!

2021-12-17 12:24 UTC, Daco2020 commented on users/views.py
> +            return JsonResponse({ "message" : "DoesNotExist" }, status=401)
잘못된 아이디를 줄때 발생하는 에러이므로 잘못된 요청인 400으로 수정하였습니다.
상태코드 401은 권한과 관련된 에러로 인증되지 않음을 의미하는 코드인데, 제가 잘못 사용하였습니다~! 감사합니다 !!

2021-12-18 11:50 UTC, Daco2020 commented
데코레이터가 메인과 병합됨에 따라 해당 내용 반영하여 새로 push 하였습니다.

2021-12-20 02:06 UTC, jamessoun93 commented
해당 PR 은 라이브코드리뷰 시간에 상세한 피드백 드릴 예정이니 잠시 보류하겠습니다.

2021-12-21 05:14 UTC, merged