[ Create ] 리스트페이지 ProductListView
wecode-bootcamp-korea/27-2nd-SUULGO-backend pull request #5
Opened 2021-12-16 09:17 UTC by yoohyeoni

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ o ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 술종류에 맞는 회원리스트 반환 페이지 작성

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 술종류에 맞는 회원리스트 반환
2. 리스트페이지 유닛테스트 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 유닛테스트 작성 방법에 대해 새로 알게되었음.

<br />

## :: 기타 질문 및 특이 사항

2021-12-16 10:11 UTC, lordmyshepherd requested changes

2021-12-16 10:11 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({'result':result_list}, status=200)
`offset`과 `limit`을 client에서 받아서 flexible하게 결과를 반환할 수 있도록 수정해주세요!

2021-12-17 09:27 UTC, jamessoun93 requested changes

2021-12-17 09:27 UTC, jamessoun93 commented on users/urls.py
> +    path('/list', ProductListView.as_view()),
`/users` vs `/users/list`
어떤 URI 구성이 더 RESTful 한지 고려해봤을때 list 라는 단어는 굳이 불필요합니다!

2021-12-17 09:27 UTC, jamessoun93 commented on users/views.py
> +        al_id   = int(request.GET.get("al_id", 0))
`al_id` 가 무슨 뜻인지 유추가 어렵습니다. 조금 더 상세한 변수명을 선택해주세요.

2021-12-17 09:27 UTC, jamessoun93 commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
이 유닛테스트가 지금 정상작동을 하나요? 저는 지금 올려주신 코드로는 정상작동을 안할것으로 보이는데 뭐가 문제일까요?

2021-12-19 08:17 UTC, yoohyeoni commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
아 !!!! 수정하였습니다 ㅎㅎㅎㅎㅎ

2021-12-21 05:18 UTC, jamessoun93 commented
충돌 해결해주세요!

2021-12-21 06:45 UTC, yoohyeoni commented
> 충돌 해결해주세요!

2021-12-21 08:11 UTC, jamessoun93 reviewed
라이브 리뷰 준비를 위한 머지 (approved 아님)

2021-12-21 08:11 UTC, jamessoun93 commented on users/views.py
> +        user_alcohol_categories = SurveyAlcoholCategory.objects.filter(alcohol_category=alcohol_category_id)[offset:offset+limit]
User 에서 시작하는 방식으로 변경.

2021-12-21 08:11 UTC, jamessoun93 commented on users/views.py
> +        users = User.objects.filter(survey__surveyalcoholcategory__alcohol_category_id=alcohol_category_id).prefetch_related('survey_set')[offset:offset+limit]
👍 👍 👍

2021-12-21 08:11 UTC, merged