[Created] 소셜 로그인 페이지 기능 구현 및 유닛 테스트
wecode-bootcamp-korea/27-2nd-SUULGO-backend pull request #6
Opened 2021-12-16 14:03 UTC by dk-sync

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 소셜 로그인, 회원가입 및 토큰 전송 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1.  카카오 소셜 로그인 기능 구현
-  데이터베이스에 유저 기록이 없을 시 필요한 정보들만 저장
-  로그인 시 유저 정보를 바탕으로 토큰 생성 후 프론트에 전송

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 유닛 테스트 관련 에러들을 수정하기 위해 에러 메시지를 읽으며 오류 사항이 무엇인지 찾는 게 힘들었습니다.
- 처음 소셜 로그인 관련 코드 작성 시, 어떻게해야 카카오쪽 로그인 서버에 연결 할 수 있는지 알아내는 것이 힘들었습니다.

<br />

## :: 기타 질문 및 특이 사항
- 유닛 테스트시 왜 test database 가 생성되는지 궁금합니다.

2021-12-17 02:04 UTC, bigfanoftim requested changes

2021-12-17 02:04 UTC, bigfanoftim commented on users/tests.py
> +        self.assertEqual(response.status_code, 200)
새롭게 생성된 유저가 아닌, 이미 존재하는 유저의 로그인 테스트도 추가해주세요~

2021-12-17 02:04 UTC, bigfanoftim commented on users/views.py
> +            )
만약 유저가 카카오 프로필 이미지를 바꾸게 되면 이에 일치하는 유저가 db에 없어 유저 데이터를 새로 만들게 될 것 같습니다. get_or_create 공식 문서를 참고하여 속성을 추가해주세요!

2021-12-17 06:38 UTC, dk-sync commented on users/views.py
> +            )
넵 update() 메소드 추가 사용하여 수정하였습니다!

2021-12-17 09:21 UTC, jamessoun93 commented
rebase & squash 해서 올려주세요!

2021-12-18 02:16 UTC, bigfanoftim commented on users/views.py
> +            )
update() method가 아닌 get_or_create에서 defaults를 한 번 활용해 보시겠어요?

2021-12-19 06:52 UTC, dk-sync commented on users/views.py
> +            )
넵 defaults 사용해서 다시 수정하겠습니다!

2021-12-19 07:11 UTC, dk-sync commented on users/views.py
> +            )
defaults를 사용하면 새로운 프로필 이미지가 생겼을때 업데이트가 되지않는거 같은데, 아닌가요??

2021-12-20 02:04 UTC, merged