[ Create ]  약속요청 기능 PromiseView 구현
wecode-bootcamp-korea/27-2nd-SUULGO-backend pull request #7
Opened 2021-12-16 16:48 UTC by Daco2020

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [x] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 마음에 드는 상대에게 약속을 요청하는 기능을 구현하였습니다.

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 클라이언트로부터 상대 아이디와 유저 토큰, 약속 날짜 정보를 받으면 이를 meetings 테이블에 기록합니다.
2. 날짜가 오늘보다 이전이라면 DATE_ERROR를 반환합니다.
3. 요청자가 동일한 날짜에 요청을 이미 했다면 ALREADY_EXISTS 에러를 반환합니다.
4. 요청받은 상대가 약속 수락여부를 기록할 수 있도록 meetings 테이블에 is_accept 컬럼을 추가하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 파이썬의 날짜를 어떻게 다룰 수 있는지 배울 수 있었습니다.
- 문자로 받은 날짜를 어떻게 날짜로 만들고 비교할 수 있는지 알 수 있었습니다.
- 중복체크 기능을 사용하여 요청을 남발하지 않도록 핸들링하는 방법을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항
- 테스트까지 모두 완료하였습니다.

2021-12-17 02:07 UTC, bigfanoftim requested changes

2021-12-17 02:07 UTC, bigfanoftim commented on users/tests.py
> +        self.assertEqual(response.status_code, 400)
예외 처리에 대한 테스트를 더 추가해주세요

2021-12-17 06:19 UTC, Daco2020 commented on users/tests.py
> +        self.assertEqual(response.status_code, 400)
예외처리 모두 테스트 완료하였습니다.!

2021-12-17 09:48 UTC, jamessoun93 requested changes

2021-12-17 09:48 UTC, jamessoun93 commented on users/views.py
> +            requester    = User.objects.get(id=request.user)
해당 로직은 데코레이터가 머지돼서 추가되면 없어질 부분이겠죠?

2021-12-17 09:48 UTC, jamessoun93 commented on users/views.py
> +            return JsonResponse({'message':'DoesNotExist'}, status=401)
여기도 DoesNotExist 에 401 이 달려있네요!
사실 이 exception 핸들러는 decorator 연결되면 사라져야해서 그냥 왜 401이 안어울리는지만 이해해주세요!

2021-12-17 12:38 UTC, Daco2020 commented on users/views.py
> +            requester    = User.objects.get(id=request.user)
네 해당부분은 수정예정입니다!

2021-12-17 12:38 UTC, Daco2020 commented on users/views.py
> +            return JsonResponse({'message':'DoesNotExist'}, status=401)
넵 이 부분도 수정하였습니다! 추가로 키에러 가능성이 있어 키에러 핸들링을 추가하였습니다~!

2021-12-18 11:55 UTC, Daco2020 commented
데코레이터가 메인과 머지됨에 따라 데코레이터 반영하여 새로 push 하였습니다.

2021-12-20 02:06 UTC, jamessoun93 approved these changes

2021-12-20 04:13 UTC, Daco2020 commented
컨플릭트 해결하였습니다~!

2021-12-21 09:01 UTC, merged