[CREATED] Mypage Login Info View 기능 구현
wecode-bootcamp-korea/27-2nd-SUULGO-backend pull request #9
Opened 2021-12-17 09:55 UTC by dk-sync

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 로그인 후 마이페이지 접속 시 관련 정보 불러오기 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. request 로 프론트 쪽에서 가지고 있는 토큰을 확인 후 토큰 관련 유저의 정보를 마이페이지에 띄움

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 데코레이터와 연동하여 유저 정보를 불러오는 방법에 대해 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항

2021-12-18 02:04 UTC, bigfanoftim requested changes

2021-12-18 02:04 UTC, bigfanoftim commented on users/views.py
> +class LoginInfoView(View):
유저의 프로필 정보를 보는 VIew이기 때문에 간단하게 ProfileView로 작성할 수 있을 것 같아요~
```suggestion
class ProfileView(View):
```

2021-12-18 02:04 UTC, bigfanoftim commented on users/views.py
> +        ]
로그인 한 유저가 본인의 프로필 정보를 호출하는 view가 맞다면 suggestion과 같이 수정해야 할 것 같습니다.

- 데코레이터로부터 전달받은 request.user를 활용하려고 하셨지만 데코레이터가 작성되어 있지 않아 추가해줘야 합니다.
- 그러면 그 유저의 해당하는 정보만 불러오면 될텐데, 어차피 하나의 user 인스턴스만 반환되는 filter 메소드를 써서 for loop까지 이어지는 것이 불필요해 보입니다.
- 추가로 `=`과 `:`을 기준으로 정렬해주세요~

```suggestion
    @log_in_decorator
    def get(self, request):
        user    = request.user
        results = {
            'name': user.name,
            'profile_image_url': user.profile_image_url,
            'email': user.email,
            'survey_info': [{
                'class_number': survey.class_number,
                'stack': survey.stack,
                'alcohol_limit': survey.alcohol_limit,
                'alcohol_level': survey.alcohol_level,
                'comment': survey.comment,
                'favorite_place': survey.favorite_place,
                'favorite_food': survey.favorite_food,
                'hobby': survey.hobby,
                'gender': survey.gender.name,
                'mbti_name': survey.mbti.name,
                'mbti_information': survey.mbti.information
            } for survey in user.survey_set.all() ]
        }
```

2021-12-18 02:04 UTC, bigfanoftim commented on users/tests.py
> +                            "mbti_information": "test"
이 부분도 마찬가지로 `:`을 기준으로 정렬해주세요!

2021-12-19 05:42 UTC, dk-sync commented on users/views.py
> +class LoginInfoView(View):
넵 수정하겠습니다!

2021-12-19 06:13 UTC, dk-sync commented on users/tests.py
> +                            "mbti_information": "test"
수정했습니다!

2021-12-19 06:17 UTC, dk-sync commented on users/views.py
> +        ]
말씀대로 filter 메소드를 사용하는건 별의미가 없는거 같아요, 수정했습니다!

2021-12-20 02:42 UTC, bigfanoftim approved these changes
LGTM 😎

2021-12-20 04:00 UTC, merged